[package]
name = "nxus-core"
version.workspace       = true
authors.workspace       = true
edition.workspace       = true
rust-version.workspace  = true
homepage.workspace      = true
repository.workspace    = true
license.workspace       = true
keywords.workspace      = true
categories.workspace    = true
description             = "nxus - core API"

[dependencies]
thiserror.workspace     = true
termcolor.workspace     = true
serde.workspace         = true
toml.workspace          = true
indexmap.workspace      = true
symlink.workspace       = true
include_dir.workspace   = true
tempfile.workspace      = true
zappy-core.workspace    = true
zappy-fs.workspace      = true
spinners                = { workspace = true, optional = true }

[dev-dependencies]

[features]
default = ["spinners"]
full = []
spinners = ["dep:spinners"]

[package.metadata.cargo-udeps.ignore]
normal = [
    "nxus",
    "nxus-shell",
]
development = ["criterion", "pretty_assertions"]
