use std::{
    fs,
    path::{Path, PathBuf},
};

use symlink::{remove_symlink_auto, symlink_dir};

use crate::{Cmd, CoreError, CoreResult, ProfileConfig, ResolvedConfig, Runner};

/// Ensures project-local nuttx workspace setup.
///
/// # Errors
/// Returns [`CoreError`] if:
/// - workspace root specified is a file,
/// - underlying I/O operation fails,
/// - underlying git command fails.
pub fn ensure_workspace(cfg: &ResolvedConfig) -> CoreResult<()> {
    if !cfg.workspace_root.exists() {
        fs::create_dir_all(&cfg.workspace_root)?;
    }

    if !cfg.workspace_root.is_dir() {
        return Err(CoreError::PathNotDir {
            path: cfg.workspace_root.clone(),
        });
    }

    repo_ensure(
        "nuttx",
        &cfg.nuttx_src,
        &cfg.workspace_root.join("nuttx"),
        cfg.nuttx_rev.as_ref(),
        cfg.runner,
    )?;
    repo_ensure(
        "nuttx-apps",
        &cfg.nuttx_apps_src,
        &cfg.workspace_root.join("nuttx-apps"),
        cfg.nuttx_apps_rev.as_ref(),
        cfg.runner,
    )
}

/// Links app managed by nxus to project-local workspace nuttx apps clone.
///
/// # Errors
/// Returns [`CoreError`] if:
/// - workspace not properly configured,
/// - underlying I/O operation fails.
pub fn link_app(cfg: &ResolvedConfig) -> CoreResult<()> {
    repo_check("nuttx", &cfg.workspace_root)?;
    repo_check("nuttx-apps", &cfg.workspace_root)?;

    let link_path = cfg.workspace_root.join("nuttx-apps").join("external");

    if !link_path.exists() {
        symlink_dir(&cfg.cwd, &link_path)?;
    }

    if !link_path.is_symlink() {
        return Err(CoreError::PathNotSymlink { path: link_path });
    }

    let link_target = fs::read_link(&link_path)?;

    if link_target != cfg.cwd {
        remove_symlink_auto(&link_path)?;
        symlink_dir(&cfg.cwd, &link_path)?;
    }

    Ok(())
}

/// Unlinks app from the project-local workspace nuttx apps clone.
///
/// # Errors
/// Returns [`CoreError::Io`] if an underlying I/O operation fails.
pub fn unlink_app(cfg: &ResolvedConfig) -> CoreResult<()> {
    let link_path = cfg.workspace_root.join("external");

    if link_path.exists() && link_path.is_symlink() {
        remove_symlink_auto(link_path)?;
    }

    Ok(())
}

/// Generates a kconfig config file for selected profile.
///
/// # Errors
/// Returns [`CoreError`] if:
/// - generated config target path already exists and is not a file,
/// - common config path exists but is not a file,
/// - config overlay path exists but is not a file,
/// - underlying I/O operation fails.
pub fn generate_config(cfg: &ResolvedConfig) -> CoreResult<()> {
    let config_path = cfg
        .workspace_root
        .join("configs")
        .join(&cfg.profile)
        .join("defconfig");
    let config_present = config_path.exists();

    if config_present && !config_path.is_file() {
        return Err(CoreError::PathNotFile { path: config_path });
    }

    let config_base = board_config_dir_root(cfg)
        .join(&cfg.config_base)
        .join("defconfig");

    if !config_base.exists() {
        return Err(CoreError::ConfigBaseNotFound {
            board: cfg.board.clone(),
            config_base: cfg.config_base.clone(),
        });
    }

    let common_config = cfg.cwd.join("config/common.config");
    let common_config_present = common_config.exists();

    if common_config_present && !common_config.is_file() {
        return Err(CoreError::PathNotFile {
            path: common_config,
        });
    }

    let config_overlay = cfg
        .cwd
        .join("config")
        .join(format!("{}.overlay", cfg.profile));
    let config_overlay_present = config_overlay.exists();

    if config_overlay_present && !config_overlay.is_file() {
        return Err(CoreError::PathNotFile {
            path: config_overlay,
        });
    }

    let mut config = String::new();

    push_str(
        &mut config,
        &format!(
            r#"# Generated by nxus
#
# Do not edit this file manually.
# Edit these files instead:
#   config/common.config
#   config/{}.overlay

#include "{}""#,
            cfg.profile,
            config_base.display()
        ),
    );

    if common_config_present {
        push_str(
            &mut config,
            &format!("#include \"{}\"", common_config.display()),
        );
    }

    if config_overlay_present {
        push_str(
            &mut config,
            &format!("#include \"{}\"", config_overlay.display()),
        );
    }

    if !config_present {
        fs::create_dir_all(cfg.workspace_root.join("configs").join(&cfg.profile))?;
        fs::write(config_path, config)?;
    }

    Ok(())
}

/// Links config to the board config root selected by the profile.
///
/// # Errors
/// Returns [`CoreError`] if:
/// - target path already present and is not a symlink,
/// - underlying I/O operation fails.
pub fn link_config(cfg: &ResolvedConfig) -> CoreResult<()> {
    let config_dir = cfg.workspace_root.join("configs").join(&cfg.profile);
    let link_path = board_config_dir_root(cfg).join(&cfg.profile);
    let config_present = link_path.exists();

    if config_present && !link_path.is_symlink() {
        return Err(CoreError::PathNotSymlink { path: link_path });
    }

    if !config_present {
        symlink_dir(config_dir, link_path)?;
    }

    Ok(())
}

/// Unlinks config from the board config root selected by the profile.
///
/// # Errors
/// Returns [`CoreError::Io`] if an underlying I/O operation fails.
pub fn unlink_config(
    cfg: &ResolvedConfig,
    profile_name: &str,
    profile: Option<&ProfileConfig>,
) -> CoreResult<()> {
    if let Some(profile) = profile {
        let config_link = cfg
            .workspace_root
            .join("nuttx")
            .join("boards")
            .join(&profile.arch)
            .join(&profile.family)
            .join(&profile.board)
            .join("configs")
            .join(profile_name);

        if config_link.exists() {
            remove_symlink_auto(config_link)?;
        }
    }

    Ok(())
}

/// Ensure repo is cloned, updated and checked-out to a selected revision.
fn repo_ensure(
    name: &str,
    src: &str,
    path: &Path,
    rev: Option<&String>,
    runner: Runner,
) -> CoreResult<()> {
    if !path.exists() {
        repo_clone(name, src, path, runner)?;
    }

    if !path.is_dir() {
        return Err(CoreError::PathNotDir {
            path: path.to_path_buf(),
        });
    }

    repo_update(path, runner)?;

    let Some(rev) = rev else {
        return Ok(());
    };

    repo_checkout(path, rev, runner)
}

/// Clones a remote git repository.
fn repo_clone(name: &str, src: &str, path: &Path, runner: Runner) -> CoreResult<()> {
    let cmd = Cmd::new("git").arg("clone").arg(src).arg(path);
    runner.run(
        &cmd,
        &format!("Cloning repository `{name}` to: {}", path.display()),
    )
}

/// Fetches remote data for a cloned repository.
fn repo_update(path: &Path, runner: Runner) -> CoreResult<()> {
    let cmd = Cmd::new("git").arg("-C").arg(path).args(["fetch", "--all"]);
    runner.run(
        &cmd,
        &format!("Fetching data for repository at: {}", path.display()),
    )
}

/// Checks out a cloned repository to a specific revision.
fn repo_checkout(path: &Path, rev: &str, runner: Runner) -> CoreResult<()> {
    let cmd = Cmd::new("git").arg("-C").arg(path).arg("checkout").arg(rev);
    runner.run(
        &cmd,
        &format!("Checking out revision `{rev}` at: {}", path.display()),
    )
}

/// Checks whether a repository clone exists in workspace.
fn repo_check(name: &str, workspace_root: &Path) -> CoreResult<()> {
    let repo_path = workspace_root.join(name);

    if !repo_path.exists() {
        return Err(CoreError::WorkspaceRepoMissing {
            name: name.to_owned(),
            workspace_root: workspace_root.to_path_buf(),
        });
    }

    if !repo_path.is_dir() {
        return Err(CoreError::PathNotDir { path: repo_path });
    }

    Ok(())
}

/// Returns the root config dir for the board selected by profile.
fn board_config_dir_root(cfg: &ResolvedConfig) -> PathBuf {
    cfg.workspace_root
        .join("nuttx")
        .join("boards")
        .join(&cfg.arch)
        .join(&cfg.family)
        .join(&cfg.board)
        .join("configs")
}

/// Pushes a &str to a String.
fn push_str(output: &mut String, line: &str) {
    output.push_str(line);
    output.push('\n');
}
