use std::fs;
use std::path::Path;

use symlink::{remove_symlink_auto, symlink_auto, symlink_dir};

use crate::{Cmd, CoreError, CoreResult, ProfileConfig, ResolvedConfig, Runner, paths};

/// Ensures project-local nuttx workspace setup.
///
/// # Errors
/// Returns [`CoreError`] if:
/// - workspace root specified is a file,
/// - underlying I/O operation fails,
/// - underlying git command fails.
pub fn ensure_workspace(cfg: &ResolvedConfig) -> CoreResult<()> {
    if !cfg.workspace_root.exists() {
        fs::create_dir_all(&cfg.workspace_root)?;
    }

    if !cfg.workspace_root.is_dir() {
        return Err(CoreError::PathNotDir {
            path: cfg.workspace_root.clone(),
        });
    }

    repo_ensure(
        "nuttx",
        &cfg.nuttx_src,
        &paths::nuttx(cfg),
        cfg.nuttx_rev.as_ref(),
        cfg.runner,
    )?;
    repo_ensure(
        "nuttx-apps",
        &cfg.nuttx_apps_src,
        &paths::nuttx_apps(cfg),
        cfg.nuttx_apps_rev.as_ref(),
        cfg.runner,
    )
}

/// Links app managed by nxus to project-local workspace nuttx apps clone.
///
/// # Errors
/// Returns [`CoreError`] if:
/// - workspace not properly configured,
/// - underlying I/O operation fails.
pub fn link_app(cfg: &ResolvedConfig) -> CoreResult<()> {
    repo_check("nuttx", &cfg.workspace_root)?;
    repo_check("nuttx-apps", &cfg.workspace_root)?;

    let link_path = paths::app_link(cfg);

    if !link_path.exists() {
        symlink_dir(&cfg.cwd, &link_path)?;
    }

    if !link_path.is_symlink() {
        return Err(CoreError::PathNotSymlink { path: link_path });
    }

    let link_target = fs::read_link(&link_path)?;

    if link_target != cfg.cwd {
        remove_symlink_auto(&link_path)?;
        symlink_dir(&cfg.cwd, &link_path)?;
    }

    Ok(())
}

/// Unlinks app from the project-local workspace nuttx apps clone.
///
/// # Errors
/// Returns [`CoreError::Io`] if an underlying I/O operation fails.
pub fn unlink_app(cfg: &ResolvedConfig) -> CoreResult<()> {
    let link_path = paths::app_link(cfg);

    if link_path.exists() && link_path.is_symlink() {
        remove_symlink_auto(link_path)?;
    }

    Ok(())
}

/// Generates a kconfig config file for selected profile.
///
/// # Errors
/// Returns [`CoreError`] if:
/// - generated config target path already exists and is not a file,
/// - common config path exists but is not a file,
/// - config overlay path exists but is not a file,
/// - underlying I/O operation fails.
pub fn generate_config(cfg: &ResolvedConfig) -> CoreResult<()> {
    let config_path = paths::generated_config_file(cfg, &cfg.profile);
    let config_present = config_path.exists();

    if config_present && !config_path.is_file() {
        return Err(CoreError::PathNotFile { path: config_path });
    }

    let config_base = paths::board_config_base(cfg);

    if !config_base.exists() {
        return Err(CoreError::ConfigBaseNotFound {
            board: cfg.board.clone(),
            config_base: cfg.config_base.clone(),
        });
    }

    let common_config = paths::common_config(cfg);
    let common_config_present = common_config.exists();

    if common_config_present && !common_config.is_file() {
        return Err(CoreError::PathNotFile {
            path: common_config,
        });
    }

    let config_overlay = paths::config_overlay(cfg, &cfg.profile);
    let config_overlay_present = config_overlay.exists();

    if config_overlay_present && !config_overlay.is_file() {
        return Err(CoreError::PathNotFile {
            path: config_overlay,
        });
    }

    let mut config = String::new();

    push_str(
        &mut config,
        &format!(
            r#"# Generated by nxus
#
# Do not edit this file manually.
# Edit these files instead:
#   config/common.config
#   config/{}.overlay

#include "{}""#,
            cfg.profile,
            config_base.display()
        ),
    );

    if common_config_present {
        push_str(
            &mut config,
            &format!("#include \"{}\"", common_config.display()),
        );
    }

    if config_overlay_present {
        push_str(
            &mut config,
            &format!("#include \"{}\"", config_overlay.display()),
        );
    }

    if !config_present {
        fs::create_dir_all(paths::generated_config_dir(cfg, &cfg.profile))?;
        fs::write(config_path, config)?;
    }

    Ok(())
}

/// Links config to the board config root selected by the profile.
///
/// # Errors
/// Returns [`CoreError`] if:
/// - target path already present and is not a symlink,
/// - underlying I/O operation fails.
pub fn link_config(cfg: &ResolvedConfig) -> CoreResult<()> {
    let config_dir = paths::generated_config_dir(cfg, &cfg.profile);
    let link_path = paths::board_config_link(cfg, &cfg.profile);
    let config_present = link_path.exists();

    if config_present && !link_path.is_symlink() {
        return Err(CoreError::PathNotSymlink { path: link_path });
    }

    if !config_present {
        symlink_dir(config_dir, link_path)?;
    }

    Ok(())
}

/// Unlinks config from the board config root selected by the profile.
///
/// # Errors
/// Returns [`CoreError::Io`] if an underlying I/O operation fails.
pub fn unlink_config(
    cfg: &ResolvedConfig,
    profile_name: &str,
    profile: Option<&ProfileConfig>,
) -> CoreResult<()> {
    if let Some(profile) = profile {
        let config_link = paths::board_config_link_for_profile(cfg, profile_name, profile);

        if config_link.exists() {
            remove_symlink_auto(config_link)?;
        }
    }

    Ok(())
}

/// Links `compile_commands.json` from a specific profile build dir to build dir root.
///
/// # Errors
/// Returns:
/// - [`CoreError::PathNotDir`] if build root dir or build dir is not a dir,
/// - [`CoreError::PathNotFile`] if the target `compile_commands.json` path is not a file,
/// - [`CoreError::PathMissing`] if the target `compile_commands.json` is missing,
/// - [`CoreError::PathNotSymlink`] if `compile_commands` link exists and is not a file,
/// - [`CoreError::Io`] on underlying I/O operation failure.
pub fn link_compile_commands(cfg: &ResolvedConfig, profile_name: &str) -> CoreResult<()> {
    if !cfg.link_compile_commands {
        return Ok(());
    }

    let build_root = paths::build_root(cfg);
    let build_dir = paths::build_dir(cfg, profile_name);
    let build_dir_present = build_dir.exists();

    if build_root.exists() && !build_root.is_dir() {
        return Err(CoreError::PathNotDir { path: build_root });
    }

    if build_dir_present && !build_dir.is_dir() {
        return Err(CoreError::PathNotDir { path: build_dir });
    }

    if build_dir_present {
        let link = paths::compile_commands_link(cfg);
        let compile_commands = paths::compile_commands_for_profile(cfg, &cfg.profile);
        let link_present = link.exists();
        let compile_commands_present = compile_commands.exists();

        if link_present && !link.is_symlink() {
            return Err(CoreError::PathNotSymlink { path: link });
        }

        if link_present && link.is_symlink() {
            remove_symlink_auto(&link)?;
        }

        if !compile_commands_present {
            return Err(CoreError::PathMissing {
                path: compile_commands,
            });
        }

        if compile_commands_present && !compile_commands.is_file() {
            return Err(CoreError::PathNotFile {
                path: compile_commands,
            });
        }

        symlink_auto(compile_commands, link)?;
    }

    Ok(())
}

/// Unlinks `compile_commands.json` from build dir root.
///
/// # Errors
/// Returns [`CoreError::PathNotSymlink`] if `compile_commands.json` present in build root dir but
/// is not a symlink, or [`CoreError::Io`] on underlying I/O operation failure.
pub fn unlink_compile_commands(cfg: &ResolvedConfig) -> CoreResult<()> {
    if !cfg.link_compile_commands {
        return Ok(());
    }

    let link = paths::compile_commands_link(cfg);

    if link.exists() && !link.is_symlink() {
        return Err(CoreError::PathNotSymlink { path: link });
    }

    remove_symlink_auto(link)?;

    Ok(())
}

/// Ensure repo is cloned, updated and checked-out to a selected revision.
fn repo_ensure(
    name: &str,
    src: &str,
    path: &Path,
    rev: Option<&String>,
    runner: Runner,
) -> CoreResult<()> {
    if !path.exists() {
        repo_clone(name, src, path, runner)?;
    }

    if !path.is_dir() {
        return Err(CoreError::PathNotDir {
            path: path.to_path_buf(),
        });
    }

    repo_update(path, runner)?;

    let Some(rev) = rev else {
        return Ok(());
    };

    repo_checkout(path, rev, runner)
}

/// Clones a remote git repository.
fn repo_clone(name: &str, src: &str, path: &Path, runner: Runner) -> CoreResult<()> {
    let cmd = Cmd::new("git").arg("clone").arg(src).arg(path);
    runner.run(
        &cmd,
        &format!("Cloning repository `{name}` to: {}", path.display()),
    )
}

/// Fetches remote data for a cloned repository.
fn repo_update(path: &Path, runner: Runner) -> CoreResult<()> {
    let cmd = Cmd::new("git").arg("-C").arg(path).args(["fetch", "--all"]);
    runner.run(
        &cmd,
        &format!("Fetching data for repository at: {}", path.display()),
    )
}

/// Checks out a cloned repository to a specific revision.
fn repo_checkout(path: &Path, rev: &str, runner: Runner) -> CoreResult<()> {
    let cmd = Cmd::new("git").arg("-C").arg(path).arg("checkout").arg(rev);
    runner.run(
        &cmd,
        &format!("Checking out revision `{rev}` at: {}", path.display()),
    )
}

/// Checks whether a repository clone exists in workspace.
fn repo_check(name: &str, workspace_root: &Path) -> CoreResult<()> {
    let repo_path = workspace_root.join(name);

    if !repo_path.exists() {
        return Err(CoreError::WorkspaceRepoMissing {
            name: name.to_owned(),
            workspace_root: workspace_root.to_path_buf(),
        });
    }

    if !repo_path.is_dir() {
        return Err(CoreError::PathNotDir { path: repo_path });
    }

    Ok(())
}

/// Pushes a &str to a String.
fn push_str(output: &mut String, line: &str) {
    output.push_str(line);
    output.push('\n');
}

#[cfg(test)]
mod tests {
    use std::fs;

    use crate::tests::{profile_config, resolved_config};
    use crate::{
        CoreError, ensure_workspace, generate_config, link_app, link_config, paths, unlink_app,
        unlink_config,
    };

    fn prepare_workspace_dirs(cfg: &crate::ResolvedConfig) {
        fs::create_dir_all(paths::nuttx(cfg)).expect("nuttx dir should be created");
        fs::create_dir_all(paths::nuttx_apps(cfg)).expect("nuttx-apps dir should be created");
    }

    #[test]
    fn ensure_workspace_errors_when_root_is_not_directory() {
        let temp_dir = tempfile::TempDir::new().expect("tempdir should be created");
        let cfg = resolved_config(temp_dir.path());

        fs::write(&cfg.workspace_root, "file").expect("workspace file should be created");

        assert!(matches!(
            ensure_workspace(&cfg),
            Err(CoreError::PathNotDir { path }) if path == cfg.workspace_root
        ));
    }

    #[test]
    fn ensure_workspace_succeeds_with_existing_repo_directories() {
        let temp_dir = tempfile::TempDir::new().expect("tempdir should be created");
        let cfg = resolved_config(temp_dir.path());

        fs::create_dir_all(&cfg.workspace_root).expect("workspace root should be created");
        prepare_workspace_dirs(&cfg);

        ensure_workspace(&cfg).expect("workspace should be accepted");
    }

    #[test]
    fn link_app_creates_and_repairs_workspace_symlink() {
        let temp_dir = tempfile::TempDir::new().expect("tempdir should be created");
        let cfg = resolved_config(temp_dir.path());

        fs::create_dir_all(&cfg.cwd).expect("cwd should be created");
        prepare_workspace_dirs(&cfg);

        link_app(&cfg).expect("app link should be created");
        let link_path = paths::app_link(&cfg);
        assert!(link_path.is_symlink());
        assert_eq!(
            fs::read_link(&link_path).expect("link target should resolve"),
            cfg.cwd
        );

        unlink_app(&cfg).expect("link should be removed");
        let other_app = temp_dir.path().join("other-app");
        fs::create_dir_all(&other_app).expect("other app dir should be created");
        fs::create_dir_all(link_path.parent().expect("parent should exist"))
            .expect("parent should be created");
        symlink::symlink_dir(&other_app, &link_path).expect("wrong link should be created");

        link_app(&cfg).expect("app link should be repaired");
        assert_eq!(
            fs::read_link(&link_path).expect("link target should resolve"),
            cfg.cwd
        );
    }

    #[test]
    fn link_app_errors_when_external_is_not_symlink() {
        let temp_dir = tempfile::TempDir::new().expect("tempdir should be created");
        let cfg = resolved_config(temp_dir.path());

        prepare_workspace_dirs(&cfg);
        fs::create_dir_all(paths::app_link(&cfg)).expect("external dir should be created");

        assert!(matches!(
            link_app(&cfg),
            Err(CoreError::PathNotSymlink { .. })
        ));
    }

    #[test]
    fn unlink_app_ignores_missing_symlink() {
        let temp_dir = tempfile::TempDir::new().expect("tempdir should be created");
        let cfg = resolved_config(temp_dir.path());

        unlink_app(&cfg).expect("missing link should be ignored");
    }

    #[test]
    fn generate_config_writes_combined_defconfig() {
        let temp_dir = tempfile::TempDir::new().expect("tempdir should be created");
        let cfg = resolved_config(temp_dir.path());
        let board_base = paths::board_config_base(&cfg);

        fs::create_dir_all(board_base.parent().expect("board parent should exist"))
            .expect("board config dir should be created");
        fs::write(&board_base, "CONFIG_BASE=y\n").expect("base defconfig should be created");
        fs::create_dir_all(paths::config_root(&cfg)).expect("config root should be created");
        fs::write(paths::common_config(&cfg), "CONFIG_COMMON=y\n")
            .expect("common config should be created");
        fs::write(
            paths::config_overlay(&cfg, &cfg.profile),
            "CONFIG_PROFILE=y\n",
        )
        .expect("overlay config should be created");

        generate_config(&cfg).expect("generated config should be created");

        let generated = fs::read_to_string(paths::generated_config_file(&cfg, &cfg.profile))
            .expect("generated config should be readable");
        assert!(generated.contains("Generated by nxus"));
        assert!(generated.contains(&board_base.display().to_string()));
        assert!(generated.contains("common.config"));
        assert!(generated.contains("sim.overlay"));
    }

    #[test]
    fn generate_config_keeps_existing_output_unchanged() {
        let temp_dir = tempfile::TempDir::new().expect("tempdir should be created");
        let cfg = resolved_config(temp_dir.path());
        let generated = paths::generated_config_file(&cfg, &cfg.profile);
        let board_base = paths::board_config_base(&cfg);

        fs::create_dir_all(board_base.parent().expect("board parent should exist"))
            .expect("board config dir should be created");
        fs::write(&board_base, "CONFIG_BASE=y\n").expect("base defconfig should be created");
        fs::create_dir_all(generated.parent().expect("generated parent should exist"))
            .expect("generated parent should be created");
        fs::write(&generated, "existing\n").expect("generated file should be pre-created");

        generate_config(&cfg).expect("existing generated file should be kept");

        assert_eq!(
            fs::read_to_string(generated).expect("generated file should be readable"),
            String::from("existing\n")
        );
    }

    #[test]
    fn generate_config_validates_input_paths() {
        let temp_dir = tempfile::TempDir::new().expect("tempdir should be created");
        let cfg = resolved_config(temp_dir.path());
        let board_base = paths::board_config_base(&cfg);

        assert!(matches!(
            generate_config(&cfg),
            Err(CoreError::ConfigBaseNotFound { .. })
        ));

        fs::create_dir_all(board_base.parent().expect("board parent should exist"))
            .expect("board config dir should be created");
        fs::write(&board_base, "CONFIG_BASE=y\n").expect("base defconfig should be created");

        fs::create_dir_all(paths::config_root(&cfg)).expect("config root should be created");
        fs::create_dir_all(paths::common_config(&cfg))
            .expect("common config dir should be created");
        assert!(matches!(
            generate_config(&cfg),
            Err(CoreError::PathNotFile { .. })
        ));

        fs::remove_dir_all(paths::common_config(&cfg))
            .expect("common config dir should be removed");
        fs::create_dir_all(paths::config_overlay(&cfg, &cfg.profile))
            .expect("overlay dir should be created");
        assert!(matches!(
            generate_config(&cfg),
            Err(CoreError::PathNotFile { .. })
        ));
    }

    #[test]
    fn link_config_creates_symlink_and_validates_existing_path() {
        let temp_dir = tempfile::TempDir::new().expect("tempdir should be created");
        let cfg = resolved_config(temp_dir.path());
        let generated_dir = paths::generated_config_dir(&cfg, &cfg.profile);
        let link_path = paths::board_config_link(&cfg, &cfg.profile);

        fs::create_dir_all(&generated_dir).expect("generated config dir should be created");
        fs::create_dir_all(link_path.parent().expect("link parent should exist"))
            .expect("link parent should be created");

        link_config(&cfg).expect("link should be created");
        assert!(link_path.is_symlink());

        fs::remove_file(&link_path).expect("symlink should be removed");
        fs::write(&link_path, "not a link").expect("plain file should be created");

        assert!(matches!(
            link_config(&cfg),
            Err(CoreError::PathNotSymlink { .. })
        ));
    }

    #[test]
    fn unlink_config_removes_existing_profile_link() {
        let temp_dir = tempfile::TempDir::new().expect("tempdir should be created");
        let cfg = resolved_config(temp_dir.path());
        let profile = profile_config("arch", "family", "board", "base");
        let target = temp_dir.path().join("target");
        let link_path = paths::board_config_link_for_profile(&cfg, "prod", &profile);

        fs::create_dir_all(&target).expect("target dir should be created");
        fs::create_dir_all(link_path.parent().expect("link parent should exist"))
            .expect("link parent should be created");
        symlink::symlink_dir(&target, &link_path).expect("profile link should be created");

        unlink_config(&cfg, "prod", Some(&profile)).expect("profile link should be removed");
        assert!(!link_path.exists());

        unlink_config(&cfg, "prod", None).expect("missing profile should be ignored");
    }
}
