[package]
name = "nxus-shell"
version.workspace       = true
authors.workspace       = true
edition.workspace       = true
rust-version.workspace  = true
homepage.workspace      = true
repository.workspace    = true
license.workspace       = true
keywords.workspace      = true
categories.workspace    = true
description             = "nxus - Clap CLI, logging, UX"

[dependencies]
clap.workspace          = true

[dev-dependencies]

[package.metadata.cargo-udeps.ignore]
normal = [
    "nxus",
    "nxus-core",
]
development = ["criterion", "pretty_assertions"]
